### ISSUE TITLE
Design boards as 4 layer boards.

### ISSUE THREAD

**Issue by esden** [mithro/pmod-hdmi#14]
For high speed boards and good signal integrity the boards should be designed as 4 layer boards. Two layer is saving money in the wrong place. :D

**Comment by mithro** [comment]
@esden - Do you have any reason to believe there are signal integrity problems / issues?

**Comment by esden** [comment]
That was a gut feeling. I looked it up: http://www.ti.com/lit/an/spraar7g/spraar7g.pdf page 7. The gut feeling stemmed from a vague recollection based on the fact that you usually have signals on both sides of the PCB. In the case of these very simple boards it is probably not a problem because the reverse side of the board is a ground fill, without any holes, gaps or traces. The only remaining concern is the distance between the differential pair and the ground plane. Using a 1.6mm two layer board results in a distance of 1.6mm from the diff pair to the GND plane. Using a 4 layer board decreases that distance to the prepreg thickness that is usually much smaller than that. The change in GND plane to diff pair distance will influence the impedance of the diff pair, and it's geometry has to be calculated accordingly to match the 50ohm necessary for the data diff pairs. My high speed and RF voodoo is not strong enough to have a firm answer for you, it was more of a "I think I heard somewhere that it is important to have" GND plane closer to the diff pair. But someone with proper EE background might need to be consulted. :D 

<blockquote></blockquote>

**Comment by mithro** [comment]
Lets worry about it when we start seeing problems :-)
